apiVersion: apps/v1
kind: Deployment
metadata:
  name: photon-app-server
  namespace: photon-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photon-app-server
  template:
    metadata:
      labels:
        app: photon-app-server
    spec:
      imagePullSecrets:
        - name: aliyun-registry-secret
      containers:
        - name: photon-app-server
          image: crpi-2em0p6yu011c97dv.cn-beijing.personal.cr.aliyuncs.com/patent-res/photon-app-server:466b40dfc650ec41fa4b2b61af78baa4f4e5b4d6
          ports:
            - containerPort: 8081
          env:
            - name: ENV
              value: "dev"
          volumeMounts:
            - name: data-storage
              mountPath: /app/data
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: data-storage
          hostPath:
            path: /data/projects/app/server/storage
            type: Directory
        - name: tz-config
          hostPath:
            path: /etc/localtime
            type: File
