name: photon-app-server
image: crpi-2em0p6yu011c97dv.cn-beijing.personal.cr.aliyuncs.com/patent-res/photon-app-server
ports:
  - containerPort: 8081
env:
  - name: ENV
    value: "dev"
volumeMounts:
  - name: tz-config
    mountPath: /etc/localtime
    readOnly: true
